import type { NextPage } from "next";
import React, { useEffect, useState, useCallback, useRef } from 'react'
import Head from "next/head";
import ProceduralMesh from '../components/procedural-mesh';



  // Initialize state with undefined width/height so server and client renders match
  // Learn more here: https://joshwcomeau.com/react/the-perils-of-rehydration/

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Three.js JP portfolio</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};

export default Home;
